//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.11 at 05:34:27 PM UYT 
//


package dgi.classes.entreEmpresas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Compl_FiscalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Compl_FiscalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Compl_Fiscal_Data" type="{http://cfe.dgi.gub.uy}Compl_Fiscal_DataType"/>
 *         &lt;element ref="{http://www.w3.org/2001/04/xmlenc#}EncryptedData"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Compl_FiscalType", propOrder = {
    "encryptedData",
    "complFiscalData"
})
public class ComplFiscalType {

    @XmlElement(name = "EncryptedData", namespace = "http://www.w3.org/2001/04/xmlenc#")
    protected EncryptedData encryptedData;
    @XmlElement(name = "Compl_Fiscal_Data")
    protected ComplFiscalDataType complFiscalData;

    /**
     * Gets the value of the encryptedData property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedData }
     *     
     */
    public EncryptedData getEncryptedData() {
        return encryptedData;
    }

    /**
     * Sets the value of the encryptedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedData }
     *     
     */
    public void setEncryptedData(EncryptedData value) {
        this.encryptedData = value;
    }

    /**
     * Gets the value of the complFiscalData property.
     * 
     * @return
     *     possible object is
     *     {@link ComplFiscalDataType }
     *     
     */
    public ComplFiscalDataType getComplFiscalData() {
        return complFiscalData;
    }

    /**
     * Sets the value of the complFiscalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplFiscalDataType }
     *     
     */
    public void setComplFiscalData(ComplFiscalDataType value) {
        this.complFiscalData = value;
    }

}
