//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.19 at 04:42:35 PM UYT 
//


package dgi.classes.respuestas.sobre;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ParamConsultaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParamConsultaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Token" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="Fechahora" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParamConsultaType", namespace = "http://cfe.dgi.gub.uy", propOrder = {
    "token",
    "fechahora"
})
public class ParamConsultaType {

    @XmlElement(name = "Token", required = true)
    protected byte[] token;
    @XmlElement(name = "Fechahora", required = true)
    protected XMLGregorianCalendar fechahora;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setToken(byte[] value) {
        this.token = value;
    }

    /**
     * Gets the value of the fechahora property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechahora() {
        return fechahora;
    }

    /**
     * Sets the value of the fechahora property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechahora(XMLGregorianCalendar value) {
        this.fechahora = value;
    }

}
