package dgi.soap.consultas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-05-17T18:18:40.134-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://dgi.gub.uy", name = "WS_eFactura_ConsultasSoapPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WSEFacturaConsultasSoapPort {

    @WebMethod(operationName = "EFACCONSULTARENVIOSCFE", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARENVIOSCFE")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARENVIOSCFEResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARENVIOSCFEResponse efacconsultarenvioscfe(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARENVIOSCFE", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARENVIOSCFE parameters
    );

    @WebMethod(operationName = "EFACCONSULTARESTADOCFE", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARESTADOCFE")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARESTADOCFEResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARESTADOCFEResponse efacconsultarestadocfe(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARESTADOCFE", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARESTADOCFE parameters
    );

    @WebMethod(operationName = "EFACCONSULTARENVIOSSOBRE", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARENVIOSSOBRE")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARENVIOSSOBREResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARENVIOSSOBREResponse efacconsultarenviossobre(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARENVIOSSOBRE", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARENVIOSSOBRE parameters
    );

    @WebMethod(operationName = "EFACCONSULTARENVIOSREPORTE", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARENVIOSREPORTE")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARENVIOSREPORTEResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARENVIOSREPORTEResponse efacconsultarenviosreporte(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARENVIOSREPORTE", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARENVIOSREPORTE parameters
    );

    @WebMethod(operationName = "EFACCONSULTARRUCEMISORES", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARRUCEMISORES")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARRUCEMISORESResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARRUCEMISORESResponse efacconsultarrucemisores(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARRUCEMISORES", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARRUCEMISORES parameters
    );

    @WebMethod(operationName = "EFACCONSULTARCFERECIBIDOS", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARCFERECIBIDOS")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARCFERECIBIDOSResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARCFERECIBIDOSResponse efacconsultarcferecibidos(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARCFERECIBIDOS", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARCFERECIBIDOS parameters
    );

    @WebMethod(operationName = "EFACCONSULTARRESPUESTAREPORTE", action = "http://dgi.gub.uyaction/AWS_EFACTURA_CONSULTAS.EFACCONSULTARRESPUESTAREPORTE")
    @WebResult(name = "WS_eFactura_Consultas.EFACCONSULTARRESPUESTAREPORTEResponse", targetNamespace = "http://dgi.gub.uy", partName = "parameters")
    public WSEFacturaConsultasEFACCONSULTARRESPUESTAREPORTEResponse efacconsultarrespuestareporte(
        @WebParam(partName = "parameters", name = "WS_eFactura_Consultas.EFACCONSULTARRESPUESTAREPORTE", targetNamespace = "http://dgi.gub.uy")
        WSEFacturaConsultasEFACCONSULTARRESPUESTAREPORTE parameters
    );
}
