<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy"
  xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:ns0="DGI_Modernizacion_Consolidado" targetNamespace="DGI_Modernizacion_Consolidado">
  <wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:schema>
      <xsd:import schemaLocation="./ws_personaGetActEmpresarialPrueba.xsd1.xsd" namespace="DGI_Modernizacion_Consolidado" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="WS_PersonaGetActEmpresarial.ExecuteSoapIn">
    <wsdl:part name="parameters" element="xsns:WS_PersonaGetActEmpresarial.Execute" xmlns:xsns="DGI_Modernizacion_Consolidado" />
  </wsdl:message>
  <wsdl:message name="WS_PersonaGetActEmpresarial.ExecuteSoapOut">
    <wsdl:part name="parameters" element="xsns:WS_PersonaGetActEmpresarial.ExecuteResponse" xmlns:xsns="DGI_Modernizacion_Consolidado" />
  </wsdl:message>
  <wsdl:portType name="WS_PersonaGetActEmpresarialSoapPort">
    <wsdl:operation name="Execute">
      <wsdl:input name="ExecuteRequest" message="ns0:WS_PersonaGetActEmpresarial.ExecuteSoapIn" />
      <wsdl:output name="ExecuteResponse" message="ns0:WS_PersonaGetActEmpresarial.ExecuteSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WS_PersonaGetActEmpresarialSoapBinding" type="ns0:WS_PersonaGetActEmpresarialSoapPort">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <wsdl:operation name="Execute">
      <soap11:operation soapAction="DGI_Modernizacion_Consolidadoaction/AWS_PERSONAGETACTEMPRESARIAL.Execute" style="document" />
      <wsdl:input name="ExecuteRequest">
        <soap11:body use="literal" />
      </wsdl:input>
      <wsdl:output name="ExecuteResponse">
        <soap11:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WS_PersonaGetActEmpresarial">
    <wsp:PolicyReference URI="#policy0" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" />
    <wsdl:port name="WS_PersonaGetActEmpresarialSoapPort" binding="ns0:WS_PersonaGetActEmpresarialSoapBinding">
      <soap11:address location="https://efactura.dgi.gub.uy:6470/ePrueba/ws_personaGetActEmpresarialPrueba" />
    </wsdl:port>
  </wsdl:service>
  <wsp:Policy wsu:Id="policy0" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <dpe:summary xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200512" xmlns:dpe="http://www.datapower.com/extensions">

          <dppolicy:domain xmlns:dppolicy="http://www.datapower.com/policy">
            http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200512
          </dppolicy:domain>

          <description>
            Implements WS Security Policy 1.1 - support SignedParts
          </description>
        </dpe:summary>
        <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200512">

          <sp:Body />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
</wsdl:definitions>