//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.01 at 06:36:07 PM UYT 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://cfe.dgi.gub.uy", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		
		
					    xmlns={@XmlNs(prefix="DGICFE", namespaceURI="http://cfe.dgi.gub.uy")
					    ,@XmlNs(prefix="firma", namespaceURI="http://www.w3.org/2000/09/xmldsig#")
					    
		}
					
		
		)  
package dgi.classes.recepcion;

import javax.xml.bind.annotation.XmlNs;









