//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.01 at 06:36:07 PM UYT 
//


package dgi.classes.recepcion;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReferenciaTipo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenciaTipo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Referencia" maxOccurs="40" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NroLinRef">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}LineasInfoRef">
 *                         &lt;maxInclusive value="40"/>
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IndGlobal" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                         &lt;totalDigits value="1"/>
 *                         &lt;enumeration value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TpoDocRef" type="{http://cfe.dgi.gub.uy}CFEType" minOccurs="0"/>
 *                   &lt;element name="Serie" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="NroCFERef" type="{http://cfe.dgi.gub.uy}NroCFEType" minOccurs="0"/>
 *                   &lt;element name="RazonRef" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="90"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FechaCFEref" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenciaTipo", namespace = "http://cfe.dgi.gub.uy", propOrder = {
    "referencias"
})
public class ReferenciaTipo {

    @XmlElement(name = "Referencia")
    protected List<ReferenciaTipo.Referencia> referencias;

    /**
     * Gets the value of the referencias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenciaTipo.Referencia }
     * 
     * 
     */
    public List<ReferenciaTipo.Referencia> getReferencias() {
        if (referencias == null) {
            referencias = new ArrayList<ReferenciaTipo.Referencia>();
        }
        return this.referencias;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NroLinRef">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}LineasInfoRef">
     *               &lt;maxInclusive value="40"/>
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IndGlobal" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *               &lt;totalDigits value="1"/>
     *               &lt;enumeration value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TpoDocRef" type="{http://cfe.dgi.gub.uy}CFEType" minOccurs="0"/>
     *         &lt;element name="Serie" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="NroCFERef" type="{http://cfe.dgi.gub.uy}NroCFEType" minOccurs="0"/>
     *         &lt;element name="RazonRef" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="90"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FechaCFEref" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nroLinRef",
        "indGlobal",
        "tpoDocRef",
        "serie",
        "nroCFERef",
        "razonRef",
        "fechaCFEref"
    })
    public static class Referencia {

        @XmlElement(name = "NroLinRef", namespace = "http://cfe.dgi.gub.uy")
        protected int nroLinRef;
        @XmlElement(name = "IndGlobal", namespace = "http://cfe.dgi.gub.uy")
        protected BigInteger indGlobal;
        @XmlElement(name = "TpoDocRef", namespace = "http://cfe.dgi.gub.uy")
        protected BigInteger tpoDocRef;
        @XmlElement(name = "Serie", namespace = "http://cfe.dgi.gub.uy")
        protected String serie;
        @XmlElement(name = "NroCFERef", namespace = "http://cfe.dgi.gub.uy")
        protected BigInteger nroCFERef;
        @XmlElement(name = "RazonRef", namespace = "http://cfe.dgi.gub.uy")
        protected String razonRef;
        @XmlElement(name = "FechaCFEref", namespace = "http://cfe.dgi.gub.uy")
        protected XMLGregorianCalendar fechaCFEref;

        /**
         * Gets the value of the nroLinRef property.
         * 
         */
        public int getNroLinRef() {
            return nroLinRef;
        }

        /**
         * Sets the value of the nroLinRef property.
         * 
         */
        public void setNroLinRef(int value) {
            this.nroLinRef = value;
        }

        /**
         * Gets the value of the indGlobal property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIndGlobal() {
            return indGlobal;
        }

        /**
         * Sets the value of the indGlobal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIndGlobal(BigInteger value) {
            this.indGlobal = value;
        }

        /**
         * Gets the value of the tpoDocRef property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTpoDocRef() {
            return tpoDocRef;
        }

        /**
         * Sets the value of the tpoDocRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTpoDocRef(BigInteger value) {
            this.tpoDocRef = value;
        }

        /**
         * Gets the value of the serie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerie() {
            return serie;
        }

        /**
         * Sets the value of the serie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerie(String value) {
            this.serie = value;
        }

        /**
         * Gets the value of the nroCFERef property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNroCFERef() {
            return nroCFERef;
        }

        /**
         * Sets the value of the nroCFERef property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNroCFERef(BigInteger value) {
            this.nroCFERef = value;
        }

        /**
         * Gets the value of the razonRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazonRef() {
            return razonRef;
        }

        /**
         * Sets the value of the razonRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazonRef(String value) {
            this.razonRef = value;
        }

        /**
         * Gets the value of the fechaCFEref property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaCFEref() {
            return fechaCFEref;
        }

        /**
         * Sets the value of the fechaCFEref property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaCFEref(XMLGregorianCalendar value) {
            this.fechaCFEref = value;
        }

    }

}
