package dgi.soap.recepcion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-07-08T07:30:54.885-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "WS_eFactura", 
                  wsdlLocation = "https://efactura.dgi.gub.uy:6443/ePrueba/ws_eprueba?wsdl",
                  targetNamespace = "http://dgi.gub.uy") 
public class WSEFactura extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dgi.gub.uy", "WS_eFactura");
    public final static QName WSEFacturaSoapPort = new QName("http://dgi.gub.uy", "WS_eFacturaSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("https://efactura.dgi.gub.uy:6443/ePrueba/ws_eprueba?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSEFactura.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://efactura.dgi.gub.uy:6443/ePrueba/ws_eprueba?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSEFactura(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSEFactura(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEFactura() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSEFactura(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSEFactura(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSEFactura(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WSEFacturaSoapPort
     */
    @WebEndpoint(name = "WS_eFacturaSoapPort")
    public WSEFacturaSoapPort getWSEFacturaSoapPort() {
        return super.getPort(WSEFacturaSoapPort, WSEFacturaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSEFacturaSoapPort
     */
    @WebEndpoint(name = "WS_eFacturaSoapPort")
    public WSEFacturaSoapPort getWSEFacturaSoapPort(WebServiceFeature... features) {
        return super.getPort(WSEFacturaSoapPort, WSEFacturaSoapPort.class, features);
    }

}
